
const DATA = window.CATTI_DATA;
const COLORS = {method:'var(--method)', grammar:'var(--grammar)', vocab:'var(--vocab)', logic:'var(--logic)', sentence:'var(--sentence)', style:'var(--style)', domain:'var(--domain)', exam:'var(--exam)', practice:'var(--practice)', synonym:'var(--vocab)', register:'var(--style)', hotspot:'var(--domain)', term:'var(--domain)'};
let state={filter:'all', query:'', renderedBionic:false, currentQuiz:0};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function highlight(s,q){s=esc(s); if(!q) return s; try{return s.replace(new RegExp(`(${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig'),'<mark>$1</mark>')}catch{return s}}
function colorFor(card){let key=card.type==='grammar'?'grammar':card.type==='synonym'?'vocab':card.type==='register'?'style':card.type==='hotspot'?'domain':card.type==='term'?'domain':'method';return COLORS[key]||'var(--grammar)'}
function renderNav(){const navItems=[['#map','知识地图','method'],['#grammar','语法RSS','grammar'],['#vocab','词汇搭配','vocab'],['#long','长难句','sentence'],['#synonym','近义词','vocab'],['#register','语域转换','style'],['#hotspot','热点情景','domain'],['#quiz','互动训练','practice'],['#ai','AI训练器','exam']];
  $('.nav').innerHTML=navItems.map(([href,t,g])=>`<a href="${href}" style="--c:${COLORS[g]}"><i></i><span>${t}</span><small>›</small></a>`).join('');
  $('.mobilebar').innerHTML=navItems.map(([href,t,g])=>`<a href="${href}" style="border-color:${COLORS[g]}">${t}</a>`).join('')+'<button id="mTop">顶部</button>';
  setTimeout(()=>{$('#mTop')?.addEventListener('click',()=>scrollTo(0,0))},0)}
function renderMap(){const wrap=$('#mapCanvas'); let svg='<svg viewBox="0 0 1000 660">'; DATA.mapEdges.forEach(([a,b])=>{const n1=DATA.mapNodes.find(n=>n.id===a), n2=DATA.mapNodes.find(n=>n.id===b); if(n1&&n2) svg+=`<line x1="${n1.x+69}" y1="${n1.y+41}" x2="${n2.x+69}" y2="${n2.y+41}" stroke="rgba(90,80,70,.34)" stroke-width="3" stroke-linecap="round"/>`;}); svg+='</svg>';
  wrap.innerHTML=svg+DATA.mapNodes.map(n=>`<div class="node" data-node="${n.id}" style="--c:${COLORS[n.group]};left:${n.x}px;top:${n.y}px"><strong>${n.title}</strong><small>${n.summary.slice(0,22)}...</small></div>`).join('');
  $$('.node').forEach(el=>el.addEventListener('click',()=>selectNode(el.dataset.node)));
  selectNode('method');}
function selectNode(id){const n=DATA.mapNodes.find(x=>x.id===id); $$('.node').forEach(e=>e.classList.toggle('active',e.dataset.node===id)); if(!n)return; $('#mapDetail').style.setProperty('--c',COLORS[n.group]); $('#mapDetail').innerHTML=`<div class="detail" style="--c:${COLORS[n.group]}"><h3>${n.title}</h3><p>${n.summary}</p><ul>${n.points.map(p=>`<li>${p}</li>`).join('')}</ul><p><b>考点：</b>${n.exam}</p></div>`}
function cardHTML(card){let q=state.query; let ex=(card.examples||[]).map(e=>`<div class="example"><div class="en">${highlight(e.en,q)}</div><div class="zh">${highlight(e.zh,q)}</div></div>`).join('');
 return `<article class="rss-card" data-type="${card.type}" style="--c:${colorFor(card)}"><div class="rss-head"><div><div class="rss-title">${highlight(card.title,q)}</div><div class="rss-meta"><span class="badge">${card.type}</span><span class="chip">${highlight(card.channel,q)}</span><span class="small">${card.id}</span></div><div class="rss-summary">${highlight(card.summary,q)}</div></div><div>展开</div></div><div class="rss-body"><div class="rss-body-grid"><div class="mini good"><b>规则/搭配</b><p>${highlight(card.pattern,q)}</p></div><div class="mini"><b>考点</b><p>${highlight(card.exam,q)}</p></div><div class="mini danger"><b>误区</b><p>${highlight(card.trap,q)}</p></div><div class="mini"><b>记忆钩子</b><p>${highlight(card.memory,q)}</p></div><div class="mini" style="grid-column:1/-1"><b>标准例句</b>${ex}</div><div class="mini" style="grid-column:1/-1"><b>练习</b><p>${highlight(card.drill,q)}</p></div></div></div></article>`}
function renderFeed(target, type, limit=999){let list=DATA.cards.filter(c=> type==='all'||c.type===type); if(state.query){let q=state.query.toLowerCase(); list=list.filter(c=>JSON.stringify(c).toLowerCase().includes(q));} if(state.filter!=='all'&&type==='all') list=list.filter(c=>c.type===state.filter); list=list.slice(0,limit); $(target).innerHTML=list.map(cardHTML).join('') || '<div class="panel">没有匹配结果。</div>'; attachCards();}
function attachCards(){ $$('.rss-head').forEach(h=>h.onclick=()=>{h.parentElement.classList.toggle('open'); saveProgress();}); }
function renderAllFeeds(){ renderFeed('#grammarFeed','grammar'); renderFeed('#vocabFeed','term'); renderFeed('#synFeed','synonym'); renderFeed('#regFeed','register'); renderFeed('#hotFeed','hotspot'); renderFeed('#allFeed','all',80); updateCounts(); }
function updateCounts(){ $('#counts').innerHTML=`<div><b>${DATA.meta.grammarCount}</b>语法卡</div><div><b>${DATA.meta.termCount}</b>术语卡</div><div><b>${DATA.meta.hotspotCount}</b>热点情景</div><div><b>${DATA.meta.cardCount}</b>总卡片</div>`;}
function renderFilters(){const types=[['all','全部'],['grammar','语法'],['term','术语'],['synonym','近义词'],['register','语域'],['hotspot','热点']]; $('#filters').innerHTML=types.map(([k,v])=>`<button data-f="${k}" class="${state.filter===k?'active':''}">${v}</button>`).join(''); $$('#filters button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.f;renderFilters();renderFeed('#allFeed','all',120)});}
function renderLongLab(){const sel=$('#longSelect'); sel.innerHTML=DATA.longSentences.map(s=>`<option value="${s.id}">${s.title}</option>`).join(''); sel.onchange=()=>drawLong(sel.value); drawLong(DATA.longSentences[0].id);}
function drawLong(id){const s=DATA.longSentences.find(x=>x.id===id); $('#longSource').textContent=s.source; $('#longTrans').textContent=s.translation; $('#longLayers').innerHTML=s.layers.map((l,i)=>`<div class="layer" data-i="${i}"><b>${l[0]}</b><br><span>${l[1]}</span></div>`).join(''); $$('.layer').forEach(el=>el.onclick=()=>{ $$('.layer').forEach(x=>x.classList.remove('active')); el.classList.add('active'); $('#longHint').innerHTML=`<b>${s.layers[+el.dataset.i][0]}：</b>${s.layers[+el.dataset.i][1]}`;});}
function renderQuiz(){let q=DATA.quiz[state.currentQuiz%DATA.quiz.length]; $('#quizBox').innerHTML=`<h3>${q.question}</h3>${q.options.map((o,i)=>`<button class="quiz-opt" data-i="${i}">${o}</button>`).join('')}<p id="quizExplain" class="small"></p>`; $$('.quiz-opt').forEach(btn=>btn.onclick=()=>{let ok=+btn.dataset.i===q.answer; btn.classList.add(ok?'correct':'wrong'); $('#quizExplain').innerHTML=(ok?'正确。':'再看规则：')+q.explain;}); $('#quizProgress').textContent=`${state.currentQuiz+1} / ${DATA.quiz.length}`;}
function bionicText(text, mode){return esc(text).split(/(\s+)/).map(w=>{if(/^\s+$/.test(w))return w; if(mode==='head'){let n=Math.max(1,Math.ceil(w.length*0.38)); return `<span class="b">${w.slice(0,n)}</span>${w.slice(n)}`;} if(mode==='cons'){return w.replace(/[bcdfghjklmnpqrstvwxyz]/gi,'<span class="cons">$&</span>')} return w}).join('')}
function applyReadingMode(mode){document.body.classList.toggle('bionic',mode==='head');document.body.classList.toggle('consonant',mode==='cons'); $$('.en,.zh,.rss-title,.rss-summary,.mini p,.sentence').forEach(el=>{ if(!el.dataset.raw) el.dataset.raw=el.textContent; el.innerHTML = mode==='off'?esc(el.dataset.raw):bionicText(el.dataset.raw, mode==='head'?'head':'cons');});}
function saveProgress(){const total=$$('.rss-card').length, open=$$('.rss-card.open').length; const pct=total?Math.round(open/total*100):0; $('#progbar').style.width=pct+'%'; localStorage.setItem('catti_v5_progress', pct)}
function localCheck(){const src=$('#srcText').value, tar=$('#tarText').value; let nums=src.match(/\d+(?:\.\d+)?%?/g)||[], miss=nums.filter(n=>!tar.includes(n)); let neg=/不|未|无|not|never|no\b|without/i.test(src) && !/不|未|无|not|never|no\b|without/i.test(tar); let casual=['a lot of','things','very good','deal with','big problem'].filter(w=>tar.toLowerCase().includes(w)); let score=100-miss.length*12-(neg?18:0)-casual.length*8; score=Math.max(0,score); $('#localResult').innerHTML=`<div class="scorebox"><div><b>${score}</b>总分</div><div><b>${miss.length}</b>数字风险</div><div><b>${neg?'1':'0'}</b>否定风险</div><div><b>${casual.length}</b>口语化</div><div><b>${tar.length}</b>字符</div></div><p><b>提示：</b>${miss.length?'核对数字 '+miss.join(', ')+'。':'数字基本保留。'} ${neg?'原文有否定，译文可能漏否定。':''} ${casual.length?'建议替换：'+casual.join(', '):'语域初检较稳定。'}</p>`;}
async function aiTrain(){const key=$('#apiKey').value.trim(), base=$('#apiBase').value.trim().replace(/\/$/,''), model=$('#apiModel').value.trim(); const src=$('#srcText').value.trim(), tar=$('#tarText').value.trim(); if(!key&&!$('#useProxy').checked){alert('请输入 API Key，或勾选本地代理。');return} $('#aiResult').textContent='正在生成反馈...'; const prompt=`你是CATTI笔译训练评阅员。请按忠实度、逻辑、术语、语法、语域、可读性给分，并指出3个最高优先级修改点。原文：${src}\n译文：${tar}`; try{const url=$('#useProxy').checked?'/api/chat':`${base}/v1/chat/completions`; const headers={'Content-Type':'application/json'}; if(!$('#useProxy').checked) headers.Authorization=`Bearer ${key}`; const res=await fetch(url,{method:'POST',headers,body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:.2})}); const data=await res.json(); $('#aiResult').textContent=data.choices?.[0]?.message?.content || JSON.stringify(data,null,2)}catch(e){$('#aiResult').textContent='请求失败：'+e.message+'。浏览器直连可能受 CORS 限制，建议使用项目包里的本地代理。'}}
function bind(){renderNav();renderMap();renderFilters();renderAllFeeds();renderLongLab();renderQuiz();
  $('#search').oninput=e=>{state.query=e.target.value.trim();renderAllFeeds();renderFeed('#allFeed','all',120)}; $('#openAll').onclick=()=>{$$('.rss-card').forEach(c=>c.classList.add('open'));saveProgress()}; $('#closeAll').onclick=()=>{$$('.rss-card').forEach(c=>c.classList.remove('open'));saveProgress()};
  $('#nextQuiz').onclick=()=>{state.currentQuiz++;renderQuiz()}; $('#localCheck').onclick=localCheck; $('#aiBtn').onclick=aiTrain;
  $('#theme').onchange=e=>{document.body.classList.toggle('dark',e.target.value==='dark');document.body.classList.toggle('paper',e.target.value==='paper');document.body.classList.toggle('glass',e.target.value==='glass')};
  $('#readMode').onchange=e=>applyReadingMode(e.target.value); $('#fontSize').oninput=e=>document.documentElement.style.setProperty('--fontSize',e.target.value+'px'); $('#lineHeight').oninput=e=>document.documentElement.style.setProperty('--lineHeight',e.target.value); $('#focusSize').oninput=e=>document.documentElement.style.setProperty('--focusSize',e.target.value+'px'); $('#hlColor').oninput=e=>document.documentElement.style.setProperty('--hl',e.target.value+'66');
  $('#focusBtn').onclick=()=>document.body.classList.toggle('reading-light'); document.addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')}); $('#topBtn').onclick=()=>scrollTo(0,0); window.addEventListener('scroll',()=>{let h=document.documentElement.scrollHeight-innerHeight; $('#scrollProg').style.width=(scrollY/h*100)+'%'});}
document.addEventListener('DOMContentLoaded',bind);
