
const D = window.CATTI_DATA; const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s)); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const colors={method:'#b9835a',grammar:'#7ea7b8',logic:'#d7b56d',lexis:'#8cab86',hot:'#c98a8a',practice:'#a794bd'}; let grammarFilter='全部', bionicMode='none', sampleIdx=0, timer=10800, timerOn=false, timerHandle=null, longStep=0;
function badge(t,c='blue'){return `<span class="badge ${c}">${esc(t)}</span>`}
function renderMap(){const svg=$('#knowledgeMap'); svg.innerHTML=''; const nodeBy=Object.fromEntries(D.mapNodes.map(n=>[n.id,n])); D.mapLinks.forEach(([a,b])=>{const A=nodeBy[a],B=nodeBy[b]; if(!A||!B)return; const line=document.createElementNS('http://www.w3.org/2000/svg','line'); line.setAttribute('x1',A.x);line.setAttribute('y1',A.y);line.setAttribute('x2',B.x);line.setAttribute('y2',B.y);line.setAttribute('class','edge'); svg.appendChild(line);}); D.mapNodes.forEach(n=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g'); g.setAttribute('class','node-item'); g.setAttribute('data-id',n.id); const c=document.createElementNS('http://www.w3.org/2000/svg','circle'); c.setAttribute('cx',n.x); c.setAttribute('cy',n.y); c.setAttribute('r',n.id==='core'?58:44); c.setAttribute('class','map-'+n.group); const text=document.createElementNS('http://www.w3.org/2000/svg','text'); text.setAttribute('x',n.x); text.setAttribute('y',n.y+6); text.setAttribute('text-anchor','middle'); text.setAttribute('class','node-label'); text.textContent=n.title.length>6?n.title.slice(0,6):n.title; g.append(c,text); g.onclick=()=>showNode(n); svg.appendChild(g);}); showNode(D.mapNodes[0]);}
function showNode(n){$('#nodePanel').innerHTML=`<h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><div class="flow-tags">${n.points.map((p,i)=>badge(p,i%2?'green':'blue')).join('')}</div><div class="note-card"><b>出题方向：</b>${esc(n.exam)}</div>`;}
function renderLong(){const sel=$('#longSelect'); sel.innerHTML=D.longSentences.map((x,i)=>`<option value="${i}">${esc(x.title)}</option>`).join(''); sel.onchange=()=>loadLong(); loadLong();}
function loadLong(){longStep=0; const x=D.longSentences[$('#longSelect').value||0]; $('#longSentence').innerHTML=esc(x.source); $('#longTranslation').innerHTML=`<p><b>参考译文：</b>${esc(x.translation)}</p><p><b>提醒：</b>${esc(x.tip)}</p>`; $('#longSteps').innerHTML=''; $('#longFeedback').innerHTML=''; $('#longUser').value='';}
function stepLong(){const x=D.longSentences[$('#longSelect').value||0]; if(longStep>=x.chunks.length)return; const [frag,note]=x.chunks[longStep++]; $('#longSteps').insertAdjacentHTML('beforeend',`<div class="step"><b>${esc(frag)}</b><br>${esc(note)}</div>`); let html=esc(x.source); x.chunks.slice(0,longStep).forEach(([f])=>{html=html.replace(esc(f.replace('...','')),m=>`<span class="chunk">${m}</span>`)}); $('#longSentence').innerHTML=html;}
function renderGrammarFilters(){const cats=['全部',...new Set(D.grammarCards.map(x=>x.cat))]; $('#grammarFilters').innerHTML=cats.map(c=>`<button class="chip ${c==='全部'?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join(''); $$('.chip').forEach(b=>b.onclick=()=>{grammarFilter=b.dataset.cat; $$('.chip').forEach(x=>x.classList.remove('active')); b.classList.add('active'); renderGrammar();});}
function renderGrammar(){const arr=D.grammarCards.filter(x=>grammarFilter==='全部'||x.cat===grammarFilter); $('#grammarList').innerHTML=arr.map((g,i)=>`<details ${i<6?'open':''} data-search="${esc(Object.values(g).join(' '))}"><summary>${esc(g.title)} <span class="tag">${esc(g.cat)}</span></summary><p class="rule-line"><b>规则：</b>${esc(g.rule)}</p><p class="rule-line"><b>固定格式：</b>${esc(g.pattern)}</p><p class="rule-line"><b>考点陷阱：</b>${esc(g.trap)}</p><p><b>标准例句：</b>${esc(g.ex)}</p></details>`).join('');}
function renderSynonyms(){ $('#synonymCards').innerHTML=D.synonymGroups.map(s=>`<article class="syn-card" data-search="${esc(s.group+' '+s.items.flat().join(' '))}"><h3>${esc(s.group)}</h3>${s.items.map(([w,n,p])=>`<div class="word-row"><b>${esc(w)}</b><span>${esc(n)}<br><small>${esc(p)}</small></span></div>`).join('')}<div class="note-card"><b>考点：</b>${esc(s.test)}</div></article>`).join('');}
function renderDisciplines(){ $('#disciplineCards').innerHTML=D.disciplineCards.map(d=>`<article class="term-card" data-search="${esc(d.field+' '+d.terms.join(' '))}"><h3>${esc(d.field)}</h3><div class="term-list">${d.terms.map(t=>`<span class="term">${esc(t)}</span>`).join('')}</div><p><b>逻辑链：</b>${esc(d.logic)}</p><p><b>标准例句：</b>${esc(d.sample)}</p></article>`).join('');}
function renderHotspots(){ $('#hotspotCards').innerHTML=D.hotspots.map((h,i)=>`<article class="hot-card" data-search="${esc(h.topic+' '+h.terms.join(' '))}"><h3>${esc(h.topic)}</h3><p>${h.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join(' ')}</p><p><b>为什么重要：</b>${esc(h.why)}</p><div class="term-list">${h.terms.map(t=>`<span class="term">${esc(t)}</span>`).join('')}</div><p><b>逻辑链：</b>${esc(h.logic)}</p><button class="btn small" onclick="sendHotspot(${i})">放入AI训练</button></article>`).join(''); $('#topicSelect').innerHTML=D.hotspots.map((h,i)=>`<option value="${i}">${esc(h.topic)}</option>`).join('');}
window.sendHotspot=function(i){const h=D.hotspots[i]; $('#topicSelect').value=i; $('#aiSource').value=h.logic+'\n术语：'+h.terms.join('；')+'\n训练要求：'+h.prompt; location.hash='#ai';}
function sampleRegister(){ $('#registerInput').value='A lot of cities are trying to deal with plastic trash, but the result is not very good. They need to do more things to make sure people sort waste in the right way.'; }
function upgradeRegister(){let t=$('#registerInput').value.trim(); if(!t){sampleRegister();t=$('#registerInput').value} const pairs=[[/\ba lot of\b/gi,'a substantial number of'],[/\bdeal with\b/gi,'address'],[/\bplastic trash\b/gi,'plastic waste'],[/\bnot very good\b/gi,'limited'],[/\bdo more things\b/gi,'take further measures'],[/\bmake sure\b/gi,'ensure'],[/\bin the right way\b/gi,'properly'],[/\bget\b/gi,'obtain'],[/\bbig\b/gi,'significant'],[/\bhelp\b/gi,'facilitate']]; let out=t; pairs.forEach(([a,b])=>out=out.replace(a,b)); $('#registerOutput').innerHTML=`<p><b>改写建议：</b></p><p>${esc(out)}</p><p><b>说明：</b>${badge('口语词替换','green')} ${badge('搭配更稳','blue')} ${badge('语域更正式','yellow')}</p>`;}
function feedback(src, ans){const risks=[]; const nums=(src.match(/\d+(?:\.\d+)?%?|[一二三四五六七八九十百千万亿]+/g)||[]); const numsA=(ans.match(/\d+(?:\.\d+)?%?|[一二三四五六七八九十百千万亿]+/g)||[]); risks.push([numsA.length>=nums.length,'数字/数量',nums.length?`原文约${nums.length}个数字，译文约${numsA.length}个。`:'原文没有明显数字。']); const neg=/\b(no|not|never|without|unless|neither|nor)\b|不|未|无|除非|没有/.test(src); const negA=/\b(no|not|never|without|unless|neither|nor)\b|不|未|无|除非|没有/.test(ans); risks.push([neg===negA,'否定范围',neg?'原文含否定/条件否定，必须核对范围。':'没有明显否定。']); const logic=(src.match(/while|although|because|therefore|however|unless|provided that|as long as|despite|尽管|因为|因此|但是|除非/g)||[]).length; const logicA=(ans.match(/虽然|尽管|因为|因此|但是|除非|while|although|because|therefore|however|unless/g)||[]).length; risks.push([logicA>=Math.min(logic,1),'逻辑连接',logic?`原文有${logic}个明显逻辑标记，译文有${logicA}个。`:'没有明显连接词。']); const allTerms=D.disciplineCards.flatMap(d=>d.terms.map(t=>t.split(' ')[0].toLowerCase())).slice(0,80); const hits=allTerms.filter(t=>t.length>4 && src.toLowerCase().includes(t)); risks.push([hits.length===0 || hits.some(h=>ans.toLowerCase().includes(h)||ans.includes(h)),'术语一致',hits.length?`检测到可能术语：${hits.slice(0,6).join(', ')}`:'未检测到内置术语。']); const informal=/\bstuff\b|\bthings\b|\ba lot\b|\bdeal with\b|很不错|很多东西|搞定|东西/.test(ans); risks.push([!informal,'语域风险',informal?'译文可能偏口语，建议改成正式表达。':'没有明显口语化风险。']); return risks.map(([ok,name,msg])=>`<span class="risk ${ok?'good':'warn'}"><b>${name}</b>：${esc(msg)}</span>`).join('');}
function setupFeedback(){const run=()=>{$('#fbPanel').innerHTML=feedback($('#fbSource').value,$('#fbAnswer').value)}; $('#fbSource').oninput=run; $('#fbAnswer').oninput=run; $('#fbSource').value=D.samples[0].text; $('#fbAnswer').value='脑机接口可能帮助患者恢复一定自主能力，但其广泛使用需要关于临床安全、神经数据保护和知情同意的审慎规则。'; run();}
function renderSources(){ $('#sourceCards').innerHTML=D.sources.map(s=>`<article class="source-card"><h3>${esc(s.title)}</h3><p>${esc(s.note)}</p><a target="_blank" rel="noreferrer" href="${esc(s.url)}">打开链接</a></article>`).join('')}
function loadSample(){const s=D.samples[sampleIdx++%D.samples.length]; $('#sourceText').value=s.text; $('#answerText').value=''; $('#aiSource').value=s.text; $('#direction').value=s.dir; updateCount();}
function updateCount(){const t=$('#answerText').value, src=$('#sourceText').value; const cn=(t.match(/[\u4e00-\u9fa5]/g)||[]).length, en=(t.match(/[A-Za-z]+(?:[-'][A-Za-z]+)?/g)||[]).length; $('#wordCount').textContent=`${cn} 字 / ${en} words`; $('#offlineRubric').innerHTML=feedback(src,t);}
function showTimer(){const h=String(Math.floor(timer/3600)).padStart(2,'0'),m=String(Math.floor(timer%3600/60)).padStart(2,'0'),s=String(timer%60).padStart(2,'0');$('#timer').textContent=`${h}:${m}:${s}`}
function setupWorkbench(){loadSample();$('#loadSample').onclick=loadSample;$('#answerText').oninput=updateCount;$('#startTimer').onclick=()=>{timerOn=!timerOn;if(!timerHandle)timerHandle=setInterval(()=>{if(timerOn&&timer>0){timer--;showTimer()}},1000)};$('#resetTimer').onclick=()=>{timer=10800;timerOn=false;showTimer()};showTimer();}
function promptText(){const task=$('#aiTask').value, dir=$('#direction').value, h=D.hotspots[$('#topicSelect').value], src=$('#aiSource').value.trim(), ans=$('#aiAnswer').value.trim(); const base='你是CATTI英语笔译训练教练。请用中文，结构清晰，给出可执行修改。不要编造官方真题，只生成原创训练题。'; if(task==='scoreTranslation')return `${base}\n方向：${dir}\n请按100分评分：事实35，逻辑25，语法搭配20，语域15，格式5。逐句指出漏译、误译、时态、冠词、复数、介词、术语、逻辑和语域问题。\n原文：${src}\n译文：${ans}`; if(task==='longSentence')return `${base}\n请拆解长难句：谓语、从句、非谓语、逻辑、翻译顺序、参考译文。\n材料：${src}`; if(task==='synonymCoach')return `${base}\n围绕材料中的近义词，分析语义、搭配、强度、语域，并给出替换建议。\n材料：${src}\n译文/答案：${ans}`; if(task==='registerCoach')return `${base}\n请把以下表达改成CATTI适合的正式表达，并说明每处修改原因。\n${src||ans}`; if(task==='comprehensiveMCQ')return `${base}\n围绕${h.topic}生成12道原创综合能力单选题，覆盖语法、搭配、阅读限定和术语。给答案和解析。`; return `${base}\n围绕热点：${h.topic}\n逻辑链：${h.logic}\n术语：${h.terms.join('；')}\n生成英译汉一段、汉译英一段、参考译文、术语表、扣分点。`;}
async function runAI(){const out=$('#aiOutput'); out.textContent='请求中……'; try{const mode=$('#apiMode').value, base=$('#baseUrl').value.replace(/\/$/,''), model=$('#modelName').value, key=$('#apiKey').value; const body={model,temperature:.35,messages:[{role:'system',content:'You are a precise CATTI translation trainer.'},{role:'user',content:promptText()}]}; let url,headers={'Content-Type':'application/json'}; if(mode==='proxy')url='/api/chat'; else{url=base+'/chat/completions'; headers.Authorization='Bearer '+key} const res=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)}); if(!res.ok)throw new Error(await res.text()); const data=await res.json(); out.textContent=data.choices?.[0]?.message?.content||JSON.stringify(data,null,2);}catch(e){out.textContent='请求失败：'+e.message+'\n\n更安全且更稳定的方式：运行项目包中的本地代理：npm install && DEEPSEEK_API_KEY=你的key npm start';}}
function setupAI(){ $('#runAI').onclick=runAI; $('#clearKey').onclick=()=>{$('#apiKey').value=''; $('#aiOutput').textContent='Key 已从页面输入框清空。'};}
function newQuiz(){const qs=[...D.quiz].sort(()=>Math.random()-.5).slice(0,10); $('#quizBox').innerHTML=qs.map((q,i)=>`<div class="quiz-item"><h3>${i+1}. ${esc(q.q)}</h3>${q.opts.map((o,j)=>`<button class="btn opt" data-i="${i}" data-j="${j}">${String.fromCharCode(65+j)}. ${esc(o)}</button>`).join('')}<p class="exp hidden">${esc(q.exp)}</p></div>`).join(''); $$('.opt').forEach(b=>b.onclick=()=>{const q=qs[+b.dataset.i],item=b.closest('.quiz-item'); $$('button',item).forEach(x=>x.disabled=true); b.classList.add(+b.dataset.j===q.a?'correct':'wrong'); $$('button',item)[q.a].classList.add('correct'); $('.exp',item).classList.remove('hidden');});}
function applyReadMode(){const root=$('#readableRoot'); $$('.bwrap').forEach(el=>el.replaceWith(document.createTextNode(el.textContent))); if(bionicMode==='none')return; const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue.trim())return NodeFilter.FILTER_REJECT; if(['SCRIPT','STYLE','TEXTAREA','INPUT','SELECT','PRE','BUTTON'].includes(n.parentElement.tagName))return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT;}}); const texts=[]; while(walker.nextNode())texts.push(walker.currentNode); texts.slice(0,3500).forEach(n=>{const span=document.createElement('span');span.className='bwrap';const raw=n.nodeValue;if(bionicMode==='prefix')span.innerHTML=esc(raw).replace(/([A-Za-z]{4,}|[\u4e00-\u9fa5]{2,})/g,m=>`<b>${esc(m.slice(0,Math.ceil(m.length*.45)))}</b>${esc(m.slice(Math.ceil(m.length*.45)))}`);else span.innerHTML=esc(raw).replace(/[A-Za-z]{3,}/g,m=>m.split('').map(ch=>/[bcdfghjklmnpqrstvwxyz]/i.test(ch)?`<b>${esc(ch)}</b>`:esc(ch)).join('')); n.parentNode.replaceChild(span,n);});}
function search(q){q=q.trim().toLowerCase(); $$('.search-hit').forEach(x=>x.classList.remove('search-hit')); if(!q)return; const hit=$$('[data-search], details, article, .sentence-box').find(el=>(el.dataset.search||el.textContent).toLowerCase().includes(q)); if(hit){hit.classList.add('search-hit'); if(hit.tagName==='DETAILS')hit.open=true; hit.scrollIntoView({behavior:'smooth',block:'center'});}}
function setupUI(){ $$('[data-theme]').forEach(b=>b.onclick=()=>{document.body.className=document.body.className.replace(/theme-\w+/g,'').trim();document.body.classList.add('theme-'+b.dataset.theme);}); $('#fontSize').oninput=e=>document.documentElement.style.setProperty('--fs',e.target.value+'px'); $('#lineHeight').oninput=e=>document.documentElement.style.setProperty('--lh',e.target.value); $('#spotSize').oninput=e=>document.documentElement.style.setProperty('--spotSize',e.target.value+'px'); $('#accentColor').oninput=e=>document.documentElement.style.setProperty('--accent',e.target.value); $('#prefixBold').onclick=()=>{bionicMode=bionicMode==='prefix'?'none':'prefix';applyReadMode()}; $('#consonantBold').onclick=()=>{bionicMode=bionicMode==='consonant'?'none':'consonant';applyReadMode()}; $('#spotToggle').onclick=()=>document.body.classList.toggle('spot-on'); $('#cardFocus').onclick=()=>document.body.classList.toggle('focus-mode'); document.addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')}); document.addEventListener('click',e=>{if(!document.body.classList.contains('focus-mode'))return; const card=e.target.closest('article,details,.lab-card,.node-panel'); if(card){$$('.card-current').forEach(x=>x.classList.remove('card-current')); card.classList.add('card-current')}}); $('#expandAll').onclick=()=>$$('details').forEach(d=>d.open=true); $('#collapseAll').onclick=()=>$$('details').forEach(d=>d.open=false); $('#topBtn').onclick=()=>scrollTo({top:0,behavior:'smooth'}); $('#searchBox').oninput=e=>search(e.target.value); addEventListener('scroll',()=>{const h=document.documentElement; $('#progressBar').style.width=(h.scrollTop/(h.scrollHeight-h.clientHeight)*100)+'%'});}
function init(){renderMap();renderLong();$('#stepLong').onclick=stepLong;$('#resetLong').onclick=loadLong;$('#checkLong').onclick=()=>{$('#longFeedback').innerHTML=feedback(D.longSentences[$('#longSelect').value||0].source,$('#longUser').value)};renderGrammarFilters();renderGrammar();renderSynonyms();renderDisciplines();renderHotspots();renderSources();setupFeedback();setupWorkbench();setupAI();setupUI();$('#newQuiz').onclick=newQuiz;$('#upgradeRegister').onclick=upgradeRegister;$('#sampleRegister').onclick=sampleRegister;newQuiz();}
init();
