
const DATA = window.CATTI_DATA;
const COLORS = {method:'var(--method)', grammar:'var(--grammar)', vocab:'var(--vocab)', logic:'var(--logic)', sentence:'var(--sentence)', style:'var(--style)', domain:'var(--domain)', exam:'var(--exam)', practice:'var(--practice)', synonym:'var(--vocab)', register:'var(--style)', hotspot:'var(--domain)', term:'var(--domain)'};
let state={filter:'all', query:'', currentQuiz:0, clozeIndex:0, memStart:0, trainIndex:0, trainType:'choice', trainTopic:'all', selectedOption:null};
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function highlight(s,q){s=esc(s); if(!q)return s; try{return s.replace(new RegExp(`(${q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig'),'<mark>$1</mark>')}catch{return s}}
function colorFor(card){let key=card.type==='grammar'?'grammar':card.type==='synonym'?'vocab':card.type==='register'?'style':card.type==='hotspot'?'domain':card.type==='term'?'domain':'method';return COLORS[key]||'var(--grammar)'}
function renderNav(){const nav=[['#memory','英语记忆','practice'],['#map','知识地图','method'],['#syllabus','系统讲义','grammar'],['#all','知识流','method'],['#grammar','语法','grammar'],['#vocab','搭配','vocab'],['#long','长难句','sentence'],['#analyzer','句子标注','sentence'],['#collocation','搭配训练','vocab'],['#trainer','离线题库','practice'],['#demoBank','示范讲解','exam'],['#ai','可选AI反馈','exam']];
$('.nav').innerHTML=nav.map(([h,t,g])=>`<a href="${h}" style="--c:${COLORS[g]}"><i></i><span>${t}</span><small>›</small></a>`).join('');
$('.mobilebar').innerHTML='<button id="openDrawer">目录</button>'+nav.slice(0,5).map(([h,t,g])=>`<a href="${h}" style="border-color:${COLORS[g]}">${t}</a>`).join('')+'<a href="#trainer" style="border-color:var(--practice)">训练</a><button id="mSettingsBtn">设置</button><button id="mTop">顶部</button>';
if($('#jumpSelect'))$('#jumpSelect').innerHTML=nav.map(([h,t])=>`<option value="${h}">${t}</option>`).join('');
if($('#drawerLinks'))$('#drawerLinks').innerHTML=nav.map(([h,t,g])=>`<a href="${h}" style="--c:${COLORS[g]}">${t}</a>`).join('');
setTimeout(()=>{$('#mTop')?.addEventListener('click',()=>scrollTo(0,0));$('#mSettingsBtn')?.addEventListener('click',()=>$('#mobileSettings')?.classList.add('open'));$('#openDrawer')?.addEventListener('click',()=>$('#mobileDrawer')?.classList.add('open'));$('#closeDrawer')?.addEventListener('click',()=>$('#mobileDrawer')?.classList.remove('open'));$$('#drawerLinks a').forEach(a=>a.onclick=()=>$('#mobileDrawer')?.classList.remove('open'));$('#jumpSelect')?.addEventListener('change',e=>{location.hash=e.target.value})},0)}
function renderMap(){const wrap=$('#mapCanvas');let svg='<svg viewBox="0 0 1000 660">';DATA.mapEdges.forEach(([a,b])=>{let n1=DATA.mapNodes.find(n=>n.id===a),n2=DATA.mapNodes.find(n=>n.id===b);if(n1&&n2)svg+=`<line x1="${n1.x+69}" y1="${n1.y+41}" x2="${n2.x+69}" y2="${n2.y+41}" stroke="rgba(90,80,70,.34)" stroke-width="3" stroke-linecap="round"/>`});svg+='</svg>';wrap.innerHTML=svg+DATA.mapNodes.map(n=>`<div class="node" data-node="${n.id}" style="--c:${COLORS[n.group]};left:${n.x}px;top:${n.y}px"><strong>${n.title}</strong><small>${n.summary.slice(0,22)}...</small></div>`).join('');$$('.node').forEach(el=>el.addEventListener('click',()=>selectNode(el.dataset.node)));selectNode('method')}
function selectNode(id){let n=DATA.mapNodes.find(x=>x.id===id);$$('.node').forEach(e=>e.classList.toggle('active',e.dataset.node===id));if(!n)return;$('#mapDetail').innerHTML=`<div class="detail" style="--c:${COLORS[n.group]}"><h3>${n.title}</h3><p>${n.summary}</p><ul>${n.points.map(p=>`<li>${p}</li>`).join('')}</ul><p><b>考点：</b>${n.exam}</p></div>`}
function enStrip(card){let bits=[];(card.examples||[]).slice(0,2).forEach(e=>{if(e.en)bits.push(e.en.length>92?e.en.slice(0,92)+'…':e.en)});let patt=(card.pattern||'').split('；')[0].split(';')[0];if(patt&&patt.length<90)bits.unshift(patt);return bits.slice(0,3).map(x=>`<span class="en-chip">${highlight(x,state.query)}</span>`).join('')}
function cardHTML(card){let q=state.query, ex=(card.examples||[]).map(e=>`<div class="example"><div class="en">${highlight(e.en,q)}</div><div class="zh">${highlight(e.zh,q)}</div></div>`).join('');return `<article class="rss-card" data-type="${card.type}" style="--c:${colorFor(card)}"><div class="rss-head"><div><div class="rss-title">${highlight(card.title,q)}</div><div class="rss-meta"><span class="badge">${card.type}</span><span class="chip">${highlight(card.channel,q)}</span><span class="small">${card.id}</span></div><div class="rss-summary">${highlight(card.summary,q)}</div><div class="mini-en-strip">${enStrip(card)}</div></div><div>展开</div></div><div class="rss-body"><div class="rss-body-grid"><div class="mini good"><b>规则/搭配</b><p>${highlight(card.pattern,q)}</p></div><div class="mini"><b>考点</b><p>${highlight(card.exam,q)}</p></div><div class="mini danger"><b>误区</b><p>${highlight(card.trap,q)}</p></div><div class="mini"><b>记忆钩子</b><p>${highlight(card.memory,q)}</p></div><div class="mini" style="grid-column:1/-1"><b>标准例句</b>${ex}</div><div class="mini" style="grid-column:1/-1"><b>练习</b><p>${highlight(card.drill,q)}</p></div></div></div></article>`}
function renderFeed(target,type,limit=999){let list=DATA.cards.filter(c=>type==='all'||c.type===type);if(state.query){let q=state.query.toLowerCase();list=list.filter(c=>JSON.stringify(c).toLowerCase().includes(q))}if(state.filter!=='all'&&type==='all')list=list.filter(c=>c.type===state.filter);$(target).innerHTML=list.slice(0,limit).map(cardHTML).join('')||'<div class="panel">没有匹配结果。</div>';attachCards()}
function attachCards(){$$('.rss-head').forEach(h=>h.onclick=()=>{h.parentElement.classList.toggle('open');saveProgress()})}
function renderAllFeeds(){renderFeed('#grammarFeed','grammar');renderFeed('#vocabFeed','term');renderFeed('#synFeed','synonym');renderFeed('#regFeed','register');renderFeed('#hotFeed','hotspot');renderFeed('#allFeed','all',120);updateCounts();applyReadingMode($('#readMode')?.value||'off')}
function updateCounts(){$('#counts').innerHTML=`<div><b>${DATA.meta.grammarCount}</b>语法卡</div><div><b>${DATA.meta.termCount}</b>术语卡</div><div><b>${DATA.meta.hotspotCount}</b>热点情景</div><div><b>${DATA.meta.cardCount}</b>总卡片</div>`}
function renderFilters(){let types=[['all','全部'],['grammar','语法'],['term','术语'],['synonym','近义词'],['register','语域'],['hotspot','热点']];$('#filters').innerHTML=types.map(([k,v])=>`<button data-f="${k}" class="${state.filter===k?'active':''}">${v}</button>`).join('');$$('#filters button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.f;renderFilters();renderFeed('#allFeed','all',180)})}
function renderMemoryDeck(){let pool=DATA.cards.filter(c=>(c.examples||[]).length).flatMap(c=>c.examples.map(e=>({type:c.type,channel:c.channel,en:e.en,zh:e.zh,c:colorFor(c)}))).filter(x=>x.en&&x.en.length>25);let start=state.memStart%pool.length;let items=[...pool.slice(start,start+9),...pool.slice(0,Math.max(0,start+9-pool.length))];$('#memoryDeck').innerHTML=items.map(x=>`<div class="memory-card" style="--c:${x.c}"><div class="enline">${esc(x.en)}</div><div class="zhline">${esc(x.zh)}</div><div class="tagline"><span class="badge">${x.type}</span><span class="chip">${esc(x.channel)}</span></div></div>`).join('');applyReadingMode($('#readMode')?.value||'off')}
function renderLongLab(){let sel=$('#longSelect');sel.innerHTML=DATA.longSentences.map(s=>`<option value="${s.id}">${s.title}</option>`).join('');sel.onchange=()=>drawLong(sel.value);drawLong(DATA.longSentences[0].id)}
function drawLong(id){let s=DATA.longSentences.find(x=>x.id===id);$('#longSource').textContent=s.source;$('#longTrans').textContent=s.translation;$('#longLayers').innerHTML=s.layers.map((l,i)=>`<div class="layer" data-i="${i}"><b>${l[0]}</b><br><span>${l[1]}</span></div>`).join('');$$('.layer').forEach(el=>el.onclick=()=>{$$('.layer').forEach(x=>x.classList.remove('active'));el.classList.add('active');$('#longHint').innerHTML=`<b>${s.layers[+el.dataset.i][0]}：</b>${s.layers[+el.dataset.i][1]}`})}
function analyzeSentence(){let t=esc($('#anaInput').value);const rules=[['neg',/\b(no|not|never|without|neither|nor|unless)\b/gi,'否定/排除'],['conn',/\b(although|though|whereas|while|because|since|therefore|thus|however|moreover|unless|provided that|rather than|in order to)\b/gi,'逻辑连接'],['time',/\b(over the past decade|in recent years|to date|by \d{4}|since \d{4}|by the end of|meanwhile)\b/gi,'时间信号'],['hedge',/\b(may|might|could|likely|potential|appear to|tend to|suggest)\b/gi,'缓和/可能'],['prep',/\b(access to|impact on|response to|reliance on|demand for|concerns about|resilience against|in light of|at the cost of)\b/gi,'介词搭配'],['nonfin',/\b(leading to|resulting in|aiming to|designed to|intended to|given|based on|driven by)\b/gi,'非谓语/压缩结构']];rules.forEach(([cls,re])=>{t=t.replace(re,m=>`<span class="u ${cls}">${m}</span>`)});$('#anaOutput').innerHTML=t;$('#anaLegend').innerHTML=rules.map(([cls,_,label])=>`<span><i class="u ${cls}">${label}</i></span>`).join('')}
function renderCloze(){let pool=DATA.cards.filter(c=>c.type==='term'&&c.examples?.[0]);let c=pool[state.clozeIndex%pool.length],phrase=c.title.split(' / ')[0];$('#clozeBox').innerHTML=`<div class="cloze-big">${esc(c.examples[0].zh)}</div><p>请回忆英文搭配：<span class="chip">${esc(c.channel)}</span></p><button id="showCloze" class="chip">显示答案</button><div id="clozeAnswer" class="cloze-answer"><h3>${esc(phrase)}</h3><p class="en">${esc(c.examples[0].en)}</p><p><b>规则：</b>${esc(c.pattern)}</p></div>`;$('#showCloze').onclick=()=>$('#clozeAnswer').classList.add('show')}
function renderQuiz(){let q=DATA.quiz[state.currentQuiz%DATA.quiz.length];$('#quizBox').innerHTML=`<h3>${q.question}</h3>${q.options.map((o,i)=>`<button class="quiz-opt" data-i="${i}">${o}</button>`).join('')}<p id="quizExplain" class="small"></p>`;$$('.quiz-opt').forEach(btn=>btn.onclick=()=>{let ok=+btn.dataset.i===q.answer;btn.classList.add(ok?'correct':'wrong');$('#quizExplain').innerHTML=(ok?'正确。':'再看规则：')+q.explain});$('#quizProgress').textContent=`${state.currentQuiz+1} / ${DATA.quiz.length}`}

function renderSyllabus(){if(!$('#syllabusGrid'))return;$('#syllabusGrid').innerHTML=(DATA.professionalSyllabus||[]).map(x=>`<article class="lecture-card" style="--c:${COLORS[x.color]||COLORS.grammar}"><h3>${esc(x.id)} · ${esc(x.title)}</h3><p class="rule">${esc(x.rule)}</p><div class="pill-row"><span>${esc(x.category)}</span><span>考点：${esc(x.exam.slice(0,24))}…</span></div><details><summary>展开：考点 / 误区 / 例句</summary><p><b>出题方向：</b>${esc(x.exam)}</p><p><b>常见误区：</b>${esc(x.trap)}</p><p><b>记忆：</b>${esc(x.memory)}</p><div class="lecture-ex">${(x.examples||[]).map(e=>`<div><p class="en">${esc(e.en)}</p><p class="zh">${esc(e.zh)}</p></div>`).join('')}</div></details></article>`).join('');}
function trainerPool(){let pool=(DATA.trainingBank||[]).filter(q=>(state.trainType==='all'||q.type===state.trainType)&&(state.trainTopic==='all'||q.topic===state.trainTopic));return pool.length?pool:(DATA.trainingBank||[])}
function renderTrainerControls(){if(!$('#trainType'))return;let types=[['all','全部题型'],['choice','选择题'],['reading','阅读理解'],['short','短句翻译'],['cloze','搭配填空'],['error','改错润色']];$('#trainType').innerHTML=types.map(([k,v])=>`<option value="${k}">${v}</option>`).join('');let topics=['all',...new Set((DATA.trainingBank||[]).map(q=>q.topic))];$('#trainTopic').innerHTML=topics.map(t=>`<option value="${esc(t)}">${t==='all'?'全部主题':esc(t)}</option>`).join('');$('#trainType').value=state.trainType;$('#trainTopic').value=state.trainTopic;}
function renderTrainer(){if(!$('#trainQuestion'))return;let pool=trainerPool();if(!pool.length){$('#trainQuestion').innerHTML='<div class="panel">暂无题目。</div>';return}state.trainIndex=((state.trainIndex%pool.length)+pool.length)%pool.length;let q=pool[state.trainIndex];state.selectedOption=null;let head=`<div class="chips"><span class="chip">${esc(q.type)}</span><span class="chip">${esc(q.topic)}</span><span class="chip">${state.trainIndex+1}/${pool.length}</span></div><h3>${esc(q.id)} · ${esc(q.prompt)}</h3>`;let body='';
if(q.passage)body+=`<div class="q-passage">${esc(q.passage)}</div>`;
if(q.type==='choice'||q.type==='reading'){body+=`<div class="q-options">${(q.options||[]).map((o,i)=>`<button data-opt="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div>`}
else if(q.type==='cloze'){body+=`<div class="trainer-answer"><input id="trainAnswer" placeholder="输入英文搭配/答案"></div>`}
else{body+=`<div class="trainer-answer"><textarea id="trainAnswer" placeholder="在这里输入你的译文/修改后的句子"></textarea></div>`}
$('#trainQuestion').innerHTML=head+body+`<div class="toolbar"><button id="submitTrain">提交并评分</button><button id="showTrainRef">只看答案</button><button id="copyTrain">复制题目</button></div><div id="trainFeedback" class="feedback-card"></div>`;
$$('[data-opt]').forEach(b=>b.onclick=()=>{$$('[data-opt]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.selectedOption=Number(b.dataset.opt)});
$('#submitTrain').onclick=scoreTrainer;$('#showTrainRef').onclick=()=>showTrainerFeedback(q, null, true);$('#copyTrain').onclick=()=>{navigator.clipboard?.writeText((q.passage? q.passage+'\n':'')+q.prompt);toast('题目已复制')};}
function scoreTrainer(){let pool=trainerPool(),q=pool[state.trainIndex];let user='';let score=70,notes=[];
if(q.type==='choice'||q.type==='reading'){let ok=state.selectedOption===q.answer;score=ok?100:45;notes.push(ok?'选择正确。':'选择不正确，注意限定词和搭配。');$$('[data-opt]').forEach(b=>{let i=Number(b.dataset.opt);b.classList.toggle('correct',i===q.answer);if(i===state.selectedOption&&i!==q.answer)b.classList.add('wrong')});}
else{user=($('#trainAnswer')?.value||'').trim();let text=user.toLowerCase();let kws=q.keywords||[];let hit=kws.filter(k=>text.includes(String(k).toLowerCase().split('/')[0].trim())).length;score=Math.min(98,Math.round((hit/Math.max(1,kws.length))*70+20));if(!user)score=0;if(/\d/.test(q.prompt)){let nums=q.prompt.match(/\d+(?:\.\d+)?%?/g)||[],miss=nums.filter(n=>!user.includes(n));score-=miss.length*12;if(miss.length)notes.push('数字可能漏译：'+miss.join(', '));}if(/although|尽管|虽然|but|但是/.test(q.prompt+q.passage)&&!/although|though|while|despite|but|however|yet|但|尽管|虽然/.test(user)) {score-=10;notes.push('让步/转折关系可能不清楚。')}if(q.type==='error'&&user===q.prompt){score=20;notes.push('还没有修改原句错误。')}score=Math.max(0,score);notes.push(`关键词命中 ${hit}/${Math.max(1,kws.length)}：${kws.join(' / ')}`);}showTrainerFeedback(q,score,false,notes)}
function showTrainerFeedback(q,score,refOnly=false,notes=[]){let fb=$('#trainFeedback');let sc=score==null?'—':score;fb.classList.add('show');fb.style.setProperty('--score',score||0);fb.innerHTML=`<div><span class="score-ring" style="--score:${score||0}"><span>${sc}</span></span><b>${refOnly?'参考答案':'评分反馈'}</b></div><div class="feedback-grid"><div><b>参考答案</b><p>${esc(q.reference||'')}</p></div><div><b>讲解</b><p>${esc(q.explain||'')}</p></div><div><b>易错点</b><p>${esc(q.trap||q.explain||'')}</p></div></div>${notes.length?`<div class="mini"><b>本次反馈</b>${notes.map(n=>`<p>• ${esc(n)}</p>`).join('')}</div>`:''}`;applyReadingMode($('#readMode')?.value||'off')}
function randomTrainer(){let pool=trainerPool();if(pool.length){state.trainIndex=Math.floor(Math.random()*pool.length);renderTrainer();}}
function localGenerateQuestion(){let cards=DATA.cards||[];let card=cards[Math.floor(Math.random()*cards.length)];let ex=(card.examples||[])[0];let q;if(ex&&Math.random()>.35){q={id:'LOCAL-'+Date.now().toString().slice(-5),type:'short',topic:card.channel||card.type,prompt:ex.zh,reference:ex.en,keywords:(card.title||'').split(/[\/；;，,]/).slice(0,3),explain:card.pattern||card.summary,trap:card.trap||'核对术语、语序、语域。'};}else{q={id:'LOCAL-'+Date.now().toString().slice(-5),type:'cloze',topic:card.channel||card.type,prompt:'请根据规则写出一个核心搭配：'+(card.summary||card.title),reference:(card.title||'').split('/')[0],keywords:[(card.title||'').split('/')[0]],explain:card.pattern||card.summary,trap:card.trap||''};}
DATA.trainingBank.unshift(q);state.trainType=q.type;state.trainTopic='all';state.trainIndex=0;renderTrainerControls();renderTrainer();toast('已从知识卡生成一题。')}
function renderDemoBank(){if(!$('#demoGrid'))return;$('#demoGrid').innerHTML=(DATA.demoBank||[]).map(d=>`<article class="demo-card"><h3>${esc(d.title)}</h3><p class="src">${esc(d.source)}</p><p><b>参考译文：</b>${esc(d.answer)}</p><details><summary>展开讲解</summary><ul>${(d.steps||[]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p><b>为什么：</b>${esc(d.why)}</p></details></article>`).join('')}
async function aiGenerateIntoTrainer(){let topic=$('#aiTopic')?.value||'CATTI热点';$('#aiQStatus').textContent='正在请求AI生成题目...';try{let txt=await requestAI(`请只输出JSON，不要markdown。生成1道CATTI笔译训练题，字段：type(choice/reading/short/cloze/error), topic, prompt, passage, options, answer, reference, keywords(array), explain, trap。主题：${topic}`);let obj=parseAIJsonSafe(txt);if(!obj)throw new Error('AI返回无法解析为JSON');obj.id='AI-'+Date.now().toString().slice(-6);if(!obj.type)obj.type='short';DATA.trainingBank.unshift(obj);state.trainType=obj.type;state.trainTopic='all';state.trainIndex=0;renderTrainerControls();renderTrainer();$('#aiQStatus').textContent='AI题目已放入训练台顶部。'}catch(e){$('#aiQStatus').textContent='AI生成失败：'+e.message+'。可用“本地随机生成一题”，不依赖API。';}}
function parseAIJsonSafe(txt){try{return JSON.parse(txt)}catch{}let m=String(txt).match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return null}
function bindTrainer(){renderTrainerControls();renderTrainer();renderDemoBank();$('#trainType')&&( $('#trainType').onchange=e=>{state.trainType=e.target.value;state.trainIndex=0;renderTrainer()} );$('#trainTopic')&&( $('#trainTopic').onchange=e=>{state.trainTopic=e.target.value;state.trainIndex=0;renderTrainer()} );$('#prevTrain')&&( $('#prevTrain').onclick=()=>{state.trainIndex--;renderTrainer()} );$('#nextTrain')&&( $('#nextTrain').onclick=()=>{state.trainIndex++;renderTrainer()} );$('#randomTrain')&&( $('#randomTrain').onclick=randomTrainer );$('#localMakeTrain')&&( $('#localMakeTrain').onclick=localGenerateQuestion );$('#aiMakeTrain')&&( $('#aiMakeTrain').onclick=aiGenerateIntoTrainer );}

function bionicText(text,mode){return esc(text).split(/(\s+)/).map(w=>{if(/^\s+$/.test(w))return w;if(mode==='head'){let n=Math.max(1,Math.ceil(w.length*.38));return `<span class="b">${w.slice(0,n)}</span>${w.slice(n)}`}if(mode==='cons')return w.replace(/[bcdfghjklmnpqrstvwxyz]/gi,'<span class="cons">$&</span>');return w}).join('')}
function applyReadingMode(mode){document.body.classList.toggle('bionic',mode==='head');document.body.classList.toggle('consonant',mode==='cons');$$('.en,.zh,.rss-title,.rss-summary,.mini p,.sentence,.enline,.zhline').forEach(el=>{if(!el.dataset.raw)el.dataset.raw=el.textContent;el.innerHTML=mode==='off'?esc(el.dataset.raw):bionicText(el.dataset.raw,mode==='head'?'head':'cons')})}
function applyTheme(v){document.body.classList.toggle('dark',v==='dark');document.body.classList.toggle('paper',v==='paper');document.body.classList.toggle('glass',v==='glass');if($('#theme'))$('#theme').value=v}
function uiSettings(){return {theme:$('#theme').value,readMode:$('#readMode').value,fontSize:$('#fontSize').value,lineHeight:$('#lineHeight').value,focusSize:$('#focusSize').value,hlColor:$('#hlColor').value}}
function applyUi(s){if(!s)return;if(s.theme)applyTheme(s.theme);if(s.readMode){$('#readMode').value=s.readMode;applyReadingMode(s.readMode)}if(s.fontSize){$('#fontSize').value=s.fontSize;document.documentElement.style.setProperty('--fontSize',s.fontSize+'px')}if(s.lineHeight){$('#lineHeight').value=s.lineHeight;document.documentElement.style.setProperty('--lineHeight',s.lineHeight)}if(s.focusSize){$('#focusSize').value=s.focusSize;document.documentElement.style.setProperty('--focusSize',s.focusSize+'px')}if(s.hlColor){$('#hlColor').value=s.hlColor;document.documentElement.style.setProperty('--hl',s.hlColor+'66')}}
function toast(msg){let d=document.createElement('div');d.textContent=msg;d.style.cssText='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:10005;background:var(--ink);color:var(--panel);padding:10px 14px;border-radius:999px;font-weight:900;box-shadow:var(--shadow)';document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function saveUi(){localStorage.setItem('catti_v6_ui',JSON.stringify(uiSettings()));toast('阅读设置已保存到本机。')}
function loadUi(){try{applyUi(JSON.parse(localStorage.getItem('catti_v6_ui')||'{}'))}catch{}}
function saveApi(){let obj={base:$('#apiBase').value,model:$('#apiModel').value,useProxy:$('#useProxy').checked};if($('#saveKey').checked)obj.key=$('#apiKey').value;localStorage.setItem('catti_v6_api',JSON.stringify(obj));toast($('#saveKey').checked?'API设置和Key已保存到本机。':'API设置已保存，Key未保存。')}
function loadApi(){try{let o=JSON.parse(localStorage.getItem('catti_v6_api')||'{}');if(o.base)$('#apiBase').value=o.base;if(o.model)$('#apiModel').value=o.model;if(o.key)$('#apiKey').value=o.key;$('#useProxy').checked=!!o.useProxy;toast('已载入API设置。')}catch{}}
function saveProgress(){let total=$$('.rss-card').length,open=$$('.rss-card.open').length,pct=total?Math.round(open/total*100):0;$('#progbar').style.width=pct+'%';localStorage.setItem('catti_v6_progress',pct)}
function localCheck(){let src=$('#srcText').value,tar=$('#tarText').value;let nums=src.match(/\d+(?:\.\d+)?%?/g)||[],miss=nums.filter(n=>!tar.includes(n));let neg=/不|未|无|not|never|no\b|without/i.test(src)&&!/不|未|无|not|never|no\b|without/i.test(tar);let casual=['a lot of','things','very good','deal with','big problem','get ','make sure'].filter(w=>tar.toLowerCase().includes(w));let logic=['although','however','therefore','because','unless','while','whereas'].filter(w=>src.toLowerCase().includes(w)&&!tar.toLowerCase().includes(w));let score=Math.max(0,100-miss.length*12-(neg?18:0)-casual.length*8-logic.length*6);$('#localResult').innerHTML=`<div class="scorebox"><div><b>${score}</b>总分</div><div><b>${miss.length}</b>数字风险</div><div><b>${neg?'1':'0'}</b>否定风险</div><div><b>${casual.length}</b>口语化</div><div><b>${logic.length}</b>逻辑词</div></div><p><b>提示：</b>${miss.length?'核对数字 '+miss.join(', ')+'。':'数字基本保留。'} ${neg?'原文有否定，译文可能漏否定。':''} ${casual.length?'建议替换：'+casual.join(', '):'语域初检较稳定。'} ${logic.length?'检查是否漏译逻辑关系：'+logic.join(', '):''}</p>`}
async function requestAI(prompt){let key=$('#apiKey').value.trim(),base=$('#apiBase').value.trim().replace(/\/$/,''),model=$('#apiModel').value.trim();if(!key&&!$('#useProxy').checked)throw new Error('请输入 API Key，或勾选本地代理。');let url=$('#useProxy').checked?'/api/chat':`${base}/v1/chat/completions`;let headers={'Content-Type':'application/json'};if(!$('#useProxy').checked)headers.Authorization=`Bearer ${key}`;let res=await fetch(url,{method:'POST',headers,body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:.2})});let data=await res.json();if(!res.ok)throw new Error(data.error?.message||JSON.stringify(data));return data.choices?.[0]?.message?.content||JSON.stringify(data,null,2)}
async function aiTrain(){let src=$('#srcText').value.trim(),tar=$('#tarText').value.trim();$('#aiResult').textContent='正在生成结构化反馈...';try{let txt=await requestAI(`你是CATTI笔译评阅员。请只输出JSON，不要markdown。字段：score, fidelity, grammar, terminology, register, priority_fixes(array), revised_translation, explanation。原文：${src}
译文：${tar}`);let obj=parseAIJsonSafe(txt);if(!obj)throw new Error('AI返回不是JSON');$('#aiResult').outerHTML='<div id="aiResult" class="ai-json-card"></div>';$('#aiResult').innerHTML=`<div class="scorebox"><div><b>${Number(obj.score)||70}</b>总分</div><div><b>${Number(obj.fidelity)||'-'}</b>忠实</div><div><b>${Number(obj.grammar)||'-'}</b>语法</div><div><b>${Number(obj.terminology)||'-'}</b>术语</div><div><b>${Number(obj.register)||'-'}</b>语域</div></div><h4>优先修改</h4>${(obj.priority_fixes||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}<h4>建议译文</h4><p class="en">${esc(obj.revised_translation||'')}</p><p>${esc(obj.explanation||'')}</p>`;applyReadingMode($('#readMode')?.value||'off')}catch(e){$('#aiResult').outerHTML='<pre id="aiResult" class="mini" style="white-space:pre-wrap"></pre>';$('#aiResult').textContent='AI请求失败：'+e.message+'。本页离线训练、题库评分仍可使用。'}}
async function testApi(){$('#aiResult').textContent='正在测试连接...';try{$('#aiResult').textContent=await requestAI('请只回复：CATTI API 连接成功。')}catch(e){$('#aiResult').textContent='测试失败：'+e.message+'。若手机浏览器无法直连，请使用本地代理或部署 serverless 代理。'}}
function bind(){renderNav();renderMemoryDeck();renderMap();renderSyllabus();renderFilters();renderAllFeeds();renderLongLab();renderQuiz();renderCloze();bindTrainer();loadUi();$('#search').oninput=e=>{state.query=e.target.value.trim();renderAllFeeds();renderFeed('#allFeed','all',180)};$('#openAll').onclick=()=>{$$('.rss-card').forEach(c=>c.classList.add('open'));saveProgress()};$('#closeAll').onclick=()=>{$$('.rss-card').forEach(c=>c.classList.remove('open'));saveProgress()};$('#shuffleMemory').onclick=()=>{state.memStart+=9;renderMemoryDeck()};$('#nextQuiz').onclick=()=>{state.currentQuiz++;renderQuiz()};$('#nextCloze').onclick=()=>{state.clozeIndex++;renderCloze()};$('#anaBtn').onclick=analyzeSentence;$('#anaClear').onclick=()=>{$('#anaOutput').textContent='';$('#anaLegend').textContent=''};analyzeSentence();$('#localCheck').onclick=localCheck;$('#aiBtn').onclick=aiTrain;$('#testApiBtn').onclick=testApi;$('#saveApiBtn').onclick=saveApi;$('#loadApiBtn').onclick=loadApi;$('#toggleKey').onclick=()=>{$('#apiKey').type=$('#apiKey').type==='password'?'text':'password'};$('#theme').onchange=e=>applyTheme(e.target.value);$('#readMode').onchange=e=>applyReadingMode(e.target.value);$('#fontSize').oninput=e=>document.documentElement.style.setProperty('--fontSize',e.target.value+'px');$('#lineHeight').oninput=e=>document.documentElement.style.setProperty('--lineHeight',e.target.value);$('#focusSize').oninput=e=>document.documentElement.style.setProperty('--focusSize',e.target.value+'px');$('#hlColor').oninput=e=>document.documentElement.style.setProperty('--hl',e.target.value+'66');$('#saveUiBtn').onclick=saveUi;$('#loadUiBtn').onclick=()=>{loadUi();toast('已载入本机设置。')};$('#focusBtn').onclick=()=>document.body.classList.toggle('reading-light');document.addEventListener('mousemove',e=>{document.documentElement.style.setProperty('--mx',e.clientX+'px');document.documentElement.style.setProperty('--my',e.clientY+'px')});$('#topBtn').onclick=()=>scrollTo(0,0);window.addEventListener('scroll',()=>{let h=document.documentElement.scrollHeight-innerHeight;$('#scrollProg').style.width=(scrollY/h*100)+'%'});$('#closeSheet').onclick=()=>$('#mobileSettings').classList.remove('open');$('#mFocus').onclick=()=>document.body.classList.toggle('reading-light');$('#mSave').onclick=saveUi;$$('#mobileSettings [data-theme]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.theme));$$('#mobileSettings [data-read]').forEach(b=>b.onclick=()=>{$('#readMode').value=b.dataset.read;applyReadingMode(b.dataset.read)});$$('#mobileSettings [data-size]').forEach(b=>b.onclick=()=>{let v=Number($('#fontSize').value)+Number(b.dataset.size);v=Math.max(14,Math.min(24,v));$('#fontSize').value=v;document.documentElement.style.setProperty('--fontSize',v+'px')})}
document.addEventListener('DOMContentLoaded',bind);
